<?php
/**
 * Created by PhpStorm.
 * User: 资霄
 * Date: 2018/8/16
 * Time: 23:47
 */

namespace app\index\controller;


use think\Controller;
use think\Session;

class Validate extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!Session::has('name')){
            $this->error("please login first",url('login/index'));
        }
    }
}